<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Route to Feature Reference Map
    |--------------------------------------------------------------------------
    |
    | Maps routes to spec section references for contextual documentation.
    | Each route can have multiple feature refs for specificity ranking.
    |
    */
    'route_feature_map' => [
        // 4.1 Contacts & Accounts
        'contacts' => ['4.1.1'],
        'contacts/{contact}' => ['4.1.1'],
        'contacts/{contact}/edit' => ['4.1.1'],
        'accounts' => ['4.1.2'],
        'accounts/{account}' => ['4.1.2'],
        'accounts/{account}/edit' => ['4.1.2'],
        'segments' => ['4.1.4'],
        'deals' => ['4.2.1'],
        'deals/board' => ['4.2.2'],
        'deals/create' => ['4.2.1'],
        'deals/{deal}' => ['4.2.1'],
        'deals/{deal}/edit' => ['4.2.1'],
        'contracts' => ['4.8.1'],
        'contracts/{contract}' => ['4.8.1'],
        'contracts/{contract}/edit' => ['4.8.1'],
        'legal' => ['4.8.3'],
        'legal/{legalMatter}' => ['4.8', '4.8.3'],
        'legal/{legalMatter}/edit' => ['4.8', '4.8.3'],
        'invoices' => ['4.9', '4.9.1'],
        'invoices/{invoice}' => ['4.9', '4.9.1'],
        'invoices/{invoice}/edit' => ['4.9', '4.9.1'],
        'vendors' => ['4.9', '4.9.2'],
        'vendors/{vendor}' => ['4.9', '4.9.2'],
        'vendors/{vendor}/edit' => ['4.9', '4.9.2'],
        'purchase-orders' => ['4.9', '4.9.3'],
        'purchase-orders/{purchaseOrder}' => ['4.9', '4.9.3'],
        'assets' => ['4.9', '4.9.5'],
        'assets/{asset}' => ['4.9', '4.9.5'],
        'employees' => ['4.9', '4.9.6'],
        'employees/{employee}' => ['4.9', '4.9.6'],
        'finance' => ['4.9', '4.9.7'],
        'support/tickets' => ['4.6', '4.6.1'],
        'support/tickets/create' => ['4.6', '4.6.1'],
        'support/tickets/{ticket}' => ['4.6', '4.6.1'],
        'support/tickets/{ticket}/edit' => ['4.6', '4.6.1'],
        'admin/omni/dashboard' => ['4.3', '4.3.1', '4.3.5'],
        'admin/omni/contact-center' => ['4.3', '4.3.5'],
        'admin/omni/tickets' => ['4.3', '4.6'],
        'admin/omni/kiosk' => ['4.3', '4.3.6'],
        'admin/interactions' => ['4.3', '4.3.2'],
        'admin/interactions/inbox' => ['4.3', '4.3.2'],
        'admin/interactions/channels' => ['4.3', '4.3.3'],
        'admin/interactions/unmatched' => ['4.3', '4.3.4'],
        'admin/integrations/marketplace' => ['4.11', '4.11.1'],
        'admin/api-tokens' => ['4.11', '4.11.2'],
        'admin/integrations' => ['4.11'],
        'admin/integrations/webhooks' => ['4.11', '4.11.3'],
        'admin/integrations/webhooks/{webhook}' => ['4.11', '4.11.3'],
        'admin/oauth-clients' => ['4.11', '4.11.4'],
        'admin/oauth-clients/{client}' => ['4.11', '4.11.4'],
        'admin/rbac' => ['4.10', '4.10.4'],
        'admin/rbac/*' => ['4.10', '4.10.4'],
        'admin/security/events' => ['4.10', '4.10.2'],
        'admin/privileged/*' => ['4.10', '4.10.3'],
        'admin/dsr' => ['4.10', '4.10.7'],
        'admin/pipelines' => ['4.2', '4.2.1'],
        'pipelines' => ['4.2', '4.2.1'],
        'pipelines/{pipeline}/board' => ['4.2.2'],
        'admin/win-loss-reasons' => ['4.2', '4.2.4'],
        'admin/quote-templates' => ['4.2', '4.2.5'],
        'admin/quotes' => ['4.2', '4.2.5'],
        'quotes' => ['4.2', '4.2.5'],
        'admin/scoring-rules' => ['4.1', '4.1.8'],
        'admin/custom-fields' => ['4.1', '4.1.6'],
        'admin/duplicates' => ['4.1', '4.1.3', '4.1.4'],
        'admin/deal-automations' => ['4.2', '4.2.3'],
        'admin/campaigns' => ['4.4', '4.4.1'],
        'admin/campaigns/{campaign}' => ['4.4', '4.4.1'],
        'admin/campaigns/{campaign}/ab-test' => ['4.4', '4.4.5'],
        'admin/campaign-templates' => ['4.4', '4.4.2'],
        'admin/campaign-templates/create' => ['4.4', '4.4.2'],
        'admin/drip-sequences' => ['4.4', '4.4.6'],
        'admin/social-posts' => ['4.4', '4.4.4'],
        'admin/tags' => ['4.4', '4.4.7'],
        'admin/analytics/campaigns-dashboard' => ['4.4', '4.4.8'],
        'admin/analytics/dashboard' => ['4.7', '4.7.1'],
        'admin/analytics/customer' => ['4.7', '4.7.2'],
        'admin/analytics/growth' => ['4.7', '4.7.3'],
        'admin/analytics/finance' => ['4.7', '4.7.4'],
        'admin/analytics/compliance' => ['4.7', '4.7.5'],
        'admin/analytics/predictive-scoring' => ['4.7', '4.7.6'],
        'admin/analytics/report-builder' => ['4.7', '4.7.7'],
        'admin/contract-templates' => ['4.8'],
        'admin/support/categories' => ['4.6', '4.6.2'],
        'admin/support/forms' => ['4.6', '4.6.1'],
        'admin/support/canned-responses' => ['4.6', '4.6.5'],
        'admin/support/sla-breaches' => ['4.6', '4.6.7'],
        'admin/sla' => ['4.6', '4.6.7'],
        'admin/sla/instances' => ['4.6', '4.6.7'],
        'admin/loyalty' => ['4.5', '4.5.1'],
        'admin/loyalty/tiers' => ['4.5', '4.5.1'],
        'admin/loyalty/rules' => ['4.5', '4.5.1'],
        'admin/loyalty/redemption-rules' => ['4.5', '4.5.1'],
        'admin/loyalty/ledger' => ['4.5', '4.5.2'],
        'admin/loyalty/enrollments' => ['4.5', '4.5.1'],
        'admin/surveys' => ['4.5', '4.5.4'],
        'admin/surveys/responses' => ['4.5', '4.5.5'],
        'admin/onboarding' => ['4.5', '4.5.6'],
        'admin/onboarding/records' => ['4.5', '4.5.6'],
        'admin/onboarding/activities' => ['4.5', '4.5.6'],
        'admin/journeys' => ['4.5', '4.5.6'],
        'admin/reactivation' => ['4.5'],
        'admin/reactivation/analytics' => ['4.5'],
        'admin/welcome-email-templates' => ['4.5', '4.5.4'],
        'admin/clv-analytics' => ['4.7', '4.7.2'],
        'admin/clv-analytics/calculations' => ['4.7', '4.7.2'],
        'calendar' => ['4.12', '4.12.1'],
        'notifications' => ['4.12', '4.12.2'],
        'admin/email/compose' => ['4.3', '4.3.7'],
        'admin/sms/compose' => ['4.3', '4.3.10'],
        'admin/call/log' => ['4.3', '4.3.8'],
        'admin/ivr/transcriptions' => ['4.3', '4.3.11'],
        'admin/chat/inbox' => ['4.3', '4.3.9'],
        'admin/field-channel' => ['4.3', '4.3.6'],
        'admin/queue-stats' => ['4.3', '4.3.5'],
        'admin/integrations/*' => ['4.11'],
        'admin/users' => ['4.10', '4.10.1'],
        'mfa/*' => ['4.10', '4.10.1'],
        'docs' => ['4.6', '4.6.2'],
        'docs/category/{category}' => ['4.6', '4.6.2'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Checklist Items by Audience
    |--------------------------------------------------------------------------
    |
    | Onboarding checklist items for each user audience type.
    |
    */
    'checklist_items' => [
        'agent' => [
            'contacts_view' => [
                'title' => 'View Contacts',
                'description' => 'Learn how to view and search contacts',
                'route' => '/contacts',
                'article_slug' => 'viewing-contacts',
            ],
            'deals_create' => [
                'title' => 'Create Deals',
                'description' => 'How to create new deals in the system',
                'route' => '/deals/create',
                'article_slug' => 'creating-deals',
            ],
            'tickets_create' => [
                'title' => 'Create Support Tickets',
                'description' => 'Creating and managing support tickets',
                'route' => '/support/tickets/create',
                'article_slug' => 'creating-tickets',
            ],
        ],
        'manager' => [
            'pipelines_manage' => [
                'title' => 'Manage Pipelines',
                'description' => 'Configure sales pipelines and stages',
                'route' => '/admin/pipelines',
                'article_slug' => 'managing-pipelines',
            ],
            'campaigns_create' => [
                'title' => 'Create Campaigns',
                'description' => 'Set up marketing campaigns',
                'route' => '/admin/campaigns/create',
                'article_slug' => 'creating-campaigns',
            ],
            'analytics_view' => [
                'title' => 'View Analytics',
                'description' => 'Access analytics and reports',
                'route' => '/admin/analytics/dashboard',
                'article_slug' => 'analytics-dashboard',
            ],
        ],
        'finance-manager' => [
            'invoices_manage' => [
                'title' => 'Manage Invoices',
                'description' => 'Create and manage customer invoices',
                'route' => '/invoices',
                'article_slug' => 'invoice-management',
            ],
            'banking_view' => [
                'title' => 'View Banking Relationships',
                'description' => 'Access and manage bank account details',
                'route' => '/banking',
                'article_slug' => 'banking',
            ],
            'vendors_manage' => [
                'title' => 'Manage Vendors',
                'description' => 'Oversee vendor relationships and procurement',
                'route' => '/vendors',
                'article_slug' => 'vendor-management',
            ],
            'purchase_orders_create' => [
                'title' => 'Create Purchase Orders',
                'description' => 'Set up procurement workflows',
                'route' => '/purchase-orders/create',
                'article_slug' => 'procurement-purchase-orders',
            ],
            'finance_dashboard' => [
                'title' => 'View Finance Dashboard',
                'description' => 'Access financial analytics and reporting',
                'route' => '/finance',
                'article_slug' => 'finance-analytics',
            ],
        ],
        'operations-manager' => [
            'assets_view' => [
                'title' => 'View Assets',
                'description' => 'Manage company assets and equipment',
                'route' => '/assets',
                'article_slug' => 'asset-management',
            ],
            'employees_view' => [
                'title' => 'View Employees',
                'description' => 'Access employee directory and records',
                'route' => '/employees',
                'article_slug' => 'employee-management',
            ],
        ],
        'admin' => [
            'users_manage' => [
                'title' => 'Manage Users',
                'description' => 'User and role management',
                'route' => '/admin/users',
                'article_slug' => 'user-management',
            ],
            'integrations_setup' => [
                'title' => 'Set Up Integrations',
                'description' => 'Connect third-party services',
                'route' => '/admin/integrations/marketplace',
                'article_slug' => 'integrations-setup',
            ],
            'rbac_configure' => [
                'title' => 'Configure RBAC',
                'description' => 'Set up permissions and roles',
                'route' => '/admin/rbac',
                'article_slug' => 'rbac-configuration',
            ],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Spec Sections
    |--------------------------------------------------------------------------
    |
    | All spec sections for coverage gap analysis.
    |
    */
    'spec_sections' => [
        '4.1' => [
            '4.1.1' => 'Contact Management',
            '4.1.2' => 'Account Management',
            '4.1.3' => 'Merge Contacts',
            '4.1.4' => 'Duplicate Detection',
            '4.1.5' => 'Timeline View',
            '4.1.6' => 'Custom Fields Management',
            '4.1.7' => 'Bulk Import/Export',
            '4.1.8' => 'Scoring Rules',
        ],
        '4.2' => [
            '4.2.1' => 'Deal Management',
            '4.2.2' => 'Pipeline Kanban Board',
            '4.2.3' => 'Deal Automations',
            '4.2.4' => 'Win/Loss Reasons',
            '4.2.5' => 'Quotes Integration',
            '4.2.6' => 'Stage Probability Forecast',
            '4.2.7' => 'Deal Comments',
        ],
        '4.3' => [
            '4.3.1' => 'Omni-Channel Dashboard',
            '4.3.2' => 'Interaction Inbox',
            '4.3.3' => 'Channels Configuration',
            '4.3.4' => 'Unmatched Items',
            '4.3.5' => 'Contact Center',
            '4.3.6' => 'Kiosk',
            '4.3.7' => 'Email Composer',
            '4.3.8' => 'Call Logging',
            '4.3.9' => 'Chat Widget',
            '4.3.10' => 'SMS Composer',
            '4.3.11' => 'Queue Stats Dashboard',
        ],
        '4.4' => [
            '4.4.1' => 'Campaigns',
            '4.4.2' => 'Campaign Templates',
            '4.4.3' => 'Email Template Editor',
            '4.4.4' => 'Multi-Channel Builder',
            '4.4.5' => 'A/B Testing',
            '4.4.6' => 'Schedule Controls',
            '4.4.7' => 'Tag Management',
            '4.4.8' => 'Campaign Analytics',
        ],
        '4.5' => [
            '4.5.1' => 'Loyalty Program',
            '4.5.2' => 'Points Ledger',
            '4.5.3' => 'Tier Display',
            '4.5.4' => 'Surveys',
            '4.5.5' => 'Survey Responses',
            '4.5.6' => 'Kiosk Interactions',
        ],
        '4.6' => [
            '4.6.1' => 'Ticket Management',
            '4.6.2' => 'Knowledge Base',
            '4.6.3' => 'Ticket Merge/Split',
            '4.6.4' => 'Internal Notes',
            '4.6.5' => 'Canned Responses',
            '4.6.6' => 'CSAT Ratings',
            '4.6.7' => 'SLA Configuration',
        ],
        '4.7' => [
            '4.7.1' => 'Analytics Dashboard',
            '4.7.2' => 'Customer Analytics',
            '4.7.3' => 'Growth Analytics',
            '4.7.4' => 'Finance Analytics',
            '4.7.5' => 'Compliance Analytics',
            '4.7.6' => 'Predictive Scoring',
            '4.7.7' => 'Report Builder',
            '4.7.8' => 'Exploratory Analysis',
            '4.7.9' => 'Revenue Forecast',
            '4.7.10' => 'Churn Risk',
            '4.7.11' => 'Time-Bucketed Forecast',
        ],
        '4.8' => [
            '4.8.1' => 'Contract Management',
            '4.8.2' => 'Contract Creation',
            '4.8.3' => 'Legal Matters',
            '4.8.4' => 'Milestone Tracking',
            '4.8.5' => 'Renewal Reminders',
            '4.8.6' => 'E-Signature Workflow',
            '4.8.7' => 'Contract Repository',
        ],
        '4.9' => [
            '4.9.1' => 'Invoice Management',
            '4.9.2' => 'Payment Recording',
            '4.9.3' => 'Bank Details',
            '4.9.4' => 'Headcount Planning',
            '4.9.5' => 'Asset Management',
            '4.9.6' => 'Procurement Approval',
            '4.9.7' => 'Ledger Summary',
        ],
        '4.10' => [
            '4.10.1' => 'MFA',
            '4.10.2' => 'Security Events',
            '4.10.3' => 'Privileged Sessions',
            '4.10.4' => 'RBAC Matrix',
            '4.10.5' => 'SSO Configuration',
            '4.10.6' => 'Data Classification',
            '4.10.7' => 'DSR Module',
        ],
        '4.11' => [
            '4.11.1' => 'Integration Marketplace',
            '4.11.2' => 'API Tokens',
            '4.11.3' => 'Webhooks',
            '4.11.4' => 'OAuth2 Authorization',
            '4.11.5' => 'Service Registry',
            '4.11.6' => 'Rate Limit Configuration',
            '4.11.7' => 'OpenAPI Documentation',
        ],
        '4.12' => [
            '4.12.1' => 'Calendar',
            '4.12.2' => 'Notifications',
            '4.12.3' => 'File Attachments',
            '4.12.4' => 'Discussion Boards',
            '4.12.5' => 'Team Calendar',
            '4.12.6' => 'Mention Dropdown',
        ],
    ],
];